### ISSUE TITLE
Fetcher throwing error

### ISSUE THREAD

**Issue by sravannerella** [coda/packs-sdk#1746]
Hi team,

I'm running into an error when triggering an API request using the `fetcher` using the following code. Please let me know if i missed anything.

Fetcher Resource: https://coda.io/packs/build/latest/samples/topic/fetcher/

**Code:**
```javascript
async function([params], context) {
    let data = await context.fetcher.fetch({method: "GET", url: "https://jsonplaceholder.typicode.com/todos/1"});
    console.log(data.response):
}
```

**Error:**
TypeError: Cannot read properties of undefined (reading 'status')
     at Object.handleFetcherStatusError (@codahq/packs-sdk/dist/bundles/thunk_bundle.js:4699:21)
...

**Environment:**
node v17.4.0
npm 8.3.1

**Comment by ekoleda-codaio** [comment]
As you can tell, we aren't actively using GitHub's issue tracker, and want to centralize support in the [Coda community](https://community.coda.io/c/developers-central/coda-packs/15). We're actually going to turn off the issue tracker for now, but if those recommendations don't work feel free to start a thread there.
